openwines:
    appellations:
        - https://fr.wikipedia.org/wiki/Coteaux-d%27ancenis
        - https://fr.wikipedia.org/wiki/Gros-plant-du-pays-nantais
        - https://fr.wikipedia.org/wiki/Muscadet_(AOC)
        - https://fr.wikipedia.org/wiki/Muscadet-s%C3%A8vre-et-maine
        - https://fr.wikipedia.org/wiki/Muscadet-coteaux-de-la-loire
        - https://fr.wikipedia.org/wiki/Muscadet-c%C3%B4tes-de-grandlieu
        - https://fr.wikipedia.org/wiki/Fiefs-vend%C3%A9ens
